- name: lakesideMaster
  hosts: lakesideMaster
  become: True
  tasks:
    # - name: Swarm leave
    #   command: docker swarm leave -f

    - name: Swarm Init
      command: docker swarm init --advertise-addr {{ inventory_hostname }}

    - name: Get Worker Token
      command: docker swarm join-token worker -q
      register: worker_token
    - name: Show Worker Token
      debug: var=worker_token.stdout
    - name: Master Token
      command: docker swarm join-token manager -q
      register: master_token
    - name: Show Master Token
      debug: var=master_token.stdout

- name: lakesideNodes
  hosts: lakesideNodes
  become: True
  vars:
    token: "{{ hostvars[groups['lakesideMaster'][0]]['worker_token']['stdout'] }}"
    master: "{{ hostvars[groups['lakesideMaster'][0]]['inventory_hostname'] }}"
  tasks:
    - name: Update the machine
      command: sudo apt update -y
    - name: Installing essentials
      command: sudo apt install docker.io docker-compose git curl -y
#      - name: Swarm leave
#        command: docker swarm leave -f
    - name: Join Swarm Cluster as a Worker
      command: docker swarm join --token {{ hostvars[groups['lakesideMaster'][0]]['worker_token']['stdout'] }} {{ hostvars[groups['lakesideMaster'][0]]['inventory_hostname'] }}:2377
      register: worker

    - name: Show Results
      debug: var=worker.stdout

    - name: Show Errors
      debug: var=worker.stderr
